name = "wanda-mattia-ap"
compatibility_date = "2026-05-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./public"

[[kv_namespaces]]
binding = "LIVE"
id = "3691ab46f89a4dfcaf2b218d4e5c2b45"
